### ISSUE TITLE
SqlUtil: update cop_plus() and cop_minus() to accept literal numeric arguments

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1066]
already came up in a practical scenario where SqlUtil could not generate the query - ex:

``` Perl
"where": ("column": cop_plus("column", 0))
```

for example to generate `where column = column + 0` (which might seem nonsense but was requested by a DBA to ensure that a certain index was used)

**Comment by gamato** [comment]
Hi. Actually many of the column operators would come useful if they could work with both literal as well as column values. The same is true for update operators as well as where operators.
Perhaps the following would be more useful instead of adding specialised operators (e.g. `op_lt` vs `op_clt`):

```
uop_prepend("string")
uop_prepend(column("colname"))
cop_plus(column("column1"), 123)
```

Or the other way around, making column name to be default and using `cop_value` wherever a literal value is needed.

**Comment by davidnich** [comment]
this works already:
```
david@meteor:~/src/qore/git/qore/build$ qore -l SqlUtil -nX '(new Table(new Datasource("pgsql:omq/omq@omq"), "jobs")).select({"columns": "jobid", "where": {"jobid": cop_plus("jobid", cop_value(0))}})'
hash: (1 member)
  jobid : list: (24 elements)
    [0]=37
    [1]=49
    [2]=9
    [3]=50
    [4]=11
    [5]=16
    [6]=2
    [7]=48
    [8]=4
    [9]=18
    [10]=7
    [11]=1
    [12]=12
    [13]=3
    [14]=45
    [15]=46
    [16]=6
    [17]=47
    [18]=5
    [19]=10
    [20]=17
    [21]=8
    [22]=52
    [23]=13
```

closing
