### ISSUE TITLE
calling a static method from within a class does not work

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#1338]
The following code does not work as expected:

```
class A {
   static string f(string p) {
       return p + "wsx";
   }
   string f() {
       return A::f("qaz");
   }
}

A a();
a.f();
```

I would expect the latter f() calls the static one and final result would be “qazwsx”.

Instead it seems the latter f() is called recursively until stack space is exhausted.

**Comment by davidnich** [comment]
as discussed in person - this has already been fixed in 0.8.13 - would be dangerous to fix in 0.8.12.\* because of the potential for breaking things.  as it is, with the fix in 0.8.13, we will probably have to implement a `%compat-broken-overload-resolution` option to ensure that existing code that relies on the current inconsistent behavior works with 0.8.13+
