### ISSUE TITLE
Implement  get_thread_call_stack()

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1779]
- simplified get_all_thread_data() 	
- get stack of current thread, no locking, just one thread.
- or any thread identified by tid ? I think current as it will correspond to get_local_vars()

**Comment by davidnich** [comment]
please note that there is already [get_all_thread_call_stacks()](https://docs.qore.org/current/lang/html/group__threading__functions.html#gaec17f040bd7b9548353563174be723c4), so you can already do:

```
list l = get_all_thread_call_stacks(){gettid()}
```

**Comment by tmandys** [comment]
Sure, but when it has two drawbacks, 1) when many thread are started then is created large hash just to get one list value, 2) lock is applied when enumerating threads, i.e. potential deadlock when debugging should be avoided

**Comment by davidnich** [comment]
@tmandys correct on both counts - also I can confirm that you will be able to read the current thread's stack trace without locking.  note that the thread stack trace lock is confusing - it's inverted in the sense that a read-write lock is used to ensure atomicity of reads - the read lock is grabbed by each thread when writing to the current thread's lock and the write lock is grabbed when reading all threads stack traces - this way each thread can write to its own stack in parallel and the read action can ensure atomicity of the read - the write lock is heavy, but because reads are rare, it was the best solution...
