### ISSUE TITLE
module-oracle: there is a memory leak in the oracle client library when encrypted connections are enabled

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1797]
this appears to be a vendor bug

it happens when a `Datasource` is shared in multiple threads and encryption is enabled

it can be solved by turning off encryption in the `sqlnet.ora` file as follows:
```
sqlnet.encryption_client=rejected
```

**Comment by pavelkveton** [comment]
ok, there is the following finding:

The problem seems to be in this scenario:

 

1.     Create datasource in thread 1 and do sql

2.     Use datasource in thread 2

3.     Something gets leaked

a.     My assumption some data from when datasource was used in thread 1

 

I have found this: https://docs.oracle.com/database/121/DBSEG/asossl.htm#DBSEG074

 

Secure Sockets Layer Usage Issues

You should be aware of SSL usage issues, such as communication with other Oracle products and types of supported authentication and encryption methods.

Consider the following issues when using SSL:

·         SSL use enables secure communication with other Oracle products, such as Oracle Internet Directory.

·         Because SSL supports both authentication and encryption, the client/server connection is somewhat slower than the standard Oracle Net TCP/IP transport (using native encryption).

·         Each SSL authentication mode requires configuration settings.

·         Multi-threaded clients currently cannot use SSL.


so it is definitely a problem in Oracle. I agree we actually cannot do anything about it, but we should definitely put this "warning" into our documentation..

**Comment by davidnich** [comment]
> Multi-threaded clients currently cannot use SSL.

wow - good find!  we definitely need to update the documentation regarding this

**Comment by pavelkveton** [comment]
ok, according to the feedback from client after checking with the Oracle admins, it is not in the SSL, since SSL is not used in our communication. So the issue would need to be in the internal Oracle encryption (driven by sqlnet.encryption_client=rejected) - we need to reproduce the problem and find out whether
- the internal Oracle encryptions is / is_not compatible with multi-thread clients
- and of it is compatible, find out where the leak is

**Comment by pvanek** [comment]
a test script
```
%new-style
const MAX = 20;

# transparent encryption of tablespace - Ora11
#const CONNSTR = "oracle:encrypt_test/encrypt_test@orcl%oracle11_2:1521";
# Ora12
const CONNSTR = "oracle:omq/omq@xbox";
#our Datasource ds(CONNSTR);
our DatasourcePool ds(CONNSTR);

on_exit ds.commit();

ds.exec("truncate table test");


our Counter c();

/*
create table test (
   id number,
   txt varchar2(10)
);
*/

sub test()
{
    c.inc();
    on_exit c.dec();

    on_exit ds.commit();

    ds.exec("insert into test values (%v, %v)", 1, 'foo');
    any r = ds.selectRow("select * from test where rownum < 2");
}

for (int i = 0; i < MAX; i++) {
  for (int j = 0 ; j < 10; j++) {
     background test();
  }
  c.waitForZero();
}

c.waitForZero();
```

cfg for sqlnet.ora (in TNS_ADMIN location)

```
pvanek@spongebob:~/src/oracle> cat sqlnet.ora 
DIAG_ADR_ENABLED = OFF
TRACE_UNIQUE_CLIENT = ON
TRACE_LEVEL_CLIENT = SUPPORT
TRACE_DIRECTORY_CLIENT = /export/home/pvanek/work
TRACE_FILE_CLIENT = trace
TRACE_TIMESTAMP_CLIENT = ON 

NAMES.DIRECTORY_PATH= (TNSNAMES)

TRACE_LEVEL_CLIENT = support
SQLNET.ENCRYPTION_CLIENT = required
SQLNET.ENCRYPTION_TYPES_CLIENT = AES256
```

**Comment by pavelkveton** [comment]
I've reproduced with oracle 12 client and the above script. Increased MAX to 2000 and looking at top, the RES memory was increasing steadily.

**Comment by pavelkveton** [comment]
this is the valgrind summary - comparison between "with encryption" (left) and "without encryption" (right), with `MAX=20`:

```
==21353== LEAK SUMMARY:                                                                  |  ==22578== LEAK SUMMARY:
==21353==    definitely lost: 56,078 bytes in 408 blocks                                 |  ==22578==    definitely lost: 2,038 bytes in 22 blocks
==21353==    indirectly lost: 3,035,141 bytes in 128,239 blocks                          |  ==22578==    indirectly lost: 188,041 bytes in 4,914 blocks
==21353==      possibly lost: 139,688 bytes in 5 blocks                                  |  ==22578==      possibly lost: 139,648 bytes in 3 blocks
==21353==    still reachable: 782,849 bytes in 1,397 blocks                              |  ==22578==    still reachable: 782,487 bytes in 1,385 blocks
==21353==                       of which reachable via heuristic:                        |  ==22578==                       of which reachable via heuristic:
==21353==                         newarray           : 24 bytes in 1 blocks              |  ==22578==                         newarray           : 24 bytes in 1 blocks
==21353==         suppressed: 0 bytes in 0 blocks                                        |  ==22578==         suppressed: 0 bytes in 0 blocks
==21353==                                                                                |  ==22578== 
==21353== For counts of detected and suppressed errors, rerun with: -v                   |  ==22578== For counts of detected and suppressed errors, rerun with: -v
==21353== Use --track-origins=yes to see where uninitialised values come from            |  ==22578== Use --track-origins=yes to see where uninitialised values come from
==21353== ERROR SUMMARY: 14600 errors from 1077 contexts (suppressed: 0 from 0)          |  ==22578== ERROR SUMMARY: 2291 errors from 1068 contexts (suppressed: 0 from 0)
```

by "no encryption" I mean the following change int sqlnet.ora:
```
SQLNET.ENCRYPTION_CLIENT = rejected
```

**Comment by pvanek** [comment]
@pavelkveton I need exact version of client for Oracle SR, please

**Comment by pavelkveton** [comment]
with @pvanek we have isolated the problem and reproduced it WITHOUT qore, using only Oracle OCI library.

Attached is the following:
* `qoci_thread_enc.cpp` - C++ code that produces memory leak with encryption on (use the attached `sqlnet.ora`)
* `enc/valgrind11.log`, `enc/valgrind121.log`, `enc/valgrind12.log` - the logs from running `qoci_thread_enc` while using Oracle Instant Client 11, 12.1.0.2.0, 12.2.0.1.0, respectively
* `qoci_thread_pw.cpp` - another C++ code that produces memory leak when we merely set the `OCI_ATTR_PASSWORD` attribute (not directly related to this issue)
* `valgrind11.log`, `valgrind121.log`, `valgrind12.log` - the logs from running `qoci_thread_pw` while using Oracle Instant Client 11, 12.1.0.2.0, 12.2.0.1.0, respectively

[code_and_valgrind_logs_issue_1797.zip](https://github.com/qorelanguage/qore/files/992602/code_and_valgrind_logs_issue_1797.zip)

It can be seen from the logs that both C++ programs produce memory leak with Oracle Instant Client 12.1.0.2.0, but not with versions 11 or 12.2.

If you don't trust `valgrind`, you can run either of the programs with arguments `10 2000` - this runs long enough to see how the memory increases in `top`, for example.

Also running the @pvanek 's qore script with Oracle client 12.1 produces the leak, while with Oracle 11 or 12.2 it does not show this huge leaking.

Conclusion: this is not a problem in Qore, but a bug in Oracle Instant Client 12.1. We strongly recommend to upgrade to Oracle Instant Client 12.2 that does not have this issue.

**Comment by pavelkveton** [comment]
setting invisible because we didn't anything anywhere in the code
