### ISSUE TITLE
add an option (global and per-field) to the FixedLengthUtil module to convert tabs to spaces

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1866]
when parsing and generating files

in our current practical case, we are generating fixed-length files for DHL with tabs and they are being rejected due to the tabs

**Comment by gamato** [comment]
When parsing, a field value can expand and become bigger than expected as per its spec.

Shall we return the longer string if user asked for tabs to spaces expansion ?

Or perhaps `truncate` option could be used with iterators too and it would make sense in exactly this use case -- if `truncate==True` then return `substr(value,0,length)`, otherwise return expanded value even if longer than `length` specifies.

What do you think ?

**Comment by davidnich** [comment]
@gamato I didn't see this comment until now for some reason

with FixedLengthUtil we can never exceed the field's character length - however I would expect a "tab to space" translation to translate 1 tab to 1 space, so that the overall field length remains the same anyway.

**Comment by gamato** [comment]
I implemented the option as `int` that says how many spaces to use instead of one tab.
