### ISSUE TITLE
string to boolean casting rather surprising and definitely confusing

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#1970]
Here's something unexpected and confusing:
```
$ qore -X 'boolean(0)'
False
$ qore -X 'boolean("0")'
False
$ qore -X 'boolean("00")'
True
```
Btw, in my opinion, any non-empty string should evaluate to True.
But at least it should be somehow logically consistent.
Still I think treating "0" as False is wrong.

**Comment by davidnich** [comment]
@gamato this was an explicit design decision that follows Perl's implementation.  In fact, changing this would break a surprising amount of code.   

It turns out that the decision made by Perl made sense even though it seems counter-intuitive.  Because of the fact that it was a conscious decision and any change would have severe effects on existing code, I'm going to close this as `notabug`.
