### ISSUE TITLE
strange behaviour of the val parameter in RangeIterator constructors and xrange() functions

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2016]
There are 2 constructors of `RangeIterator`:

`RangeIterator::constructor(int start, int stop, int step = 1, any val)`
`RangeIterator::constructor(int stop, any val)`

and 2 overloaded function `xrange()` with the same parameters:

`RangeIterator xrange(int start, int stop, int step = 1, any val)`
 `RangeIterator xrange(int stop, any val)`

Two issues:

1. the `val` parameter is declared as `any` but works only for integers,
    other types are converted to integer and moreover the destructor crashes (except for `float`s):
    `xrange(3, 7.8)` returns iterator over `(7, 7, 7, 7)`
    `xrange(2, 'x')` returns iterator over `(0, 0, 0)` and the iterator destructor crashes

2. the second constructor and xrange function cannot be called with the `val` parameter of type `int`
    because in that case the first function is called instead:
    by `xrange(5, 3)` we actually call the first function and get iterator over `(5, 4, 3)` (and not `(3,3,3,3,3,3)` as the second function would return)

**Comment by davidnich** [comment]
@pavelkveton and @martin-zemek this is another element of technical debt we need to resolve - regarding ambiguous overloaded function/method signatures.  To fix this I would suggest modifying the second method to resolve the ambiguity, leaving:
```
RangeIterator::constructor(int start, int stop, int step = 1, any val) {}
RangeIterator::constructor(int stop) {}

RangeIterator xrange(int start, int stop, int step = 1, any val) {}
RangeIterator xrange(int stop) {}
```
After a code review, I see that only the first one and the second one without the second `any val` argument are used, so the breakage will be minimized with this approach.

However, because this could break things, I believe we need to set the Milestone to 0.8.13.

Comments?

**Comment by martin-zemek** [comment]
Yes, I agree.
