### ISSUE TITLE
API to provide thread list related to program

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2086]
Implement `"list Program::get_threads()" `method to provide threads associated to particular program. Maybe opposite function `list get_programs()` might be valuable too, get program list used in current thread. Or optionally a function to return whole program/thread scenario.

**Comment by davidnich** [comment]
@tmandys we cannot implement a "get_programs()" function that returns the current `Program` object because having the current `Program` object in the program being executed is not currently safe - this is something we need to either fix so it's safe or use another approach like we discussed in the context of debugger functionality.   For now I'll implement the `list<int> Program::getThreads() {}` method, and then let's discuss the other scenario and to best cover it together.
