### ISSUE TITLE
implement a way for exceptions to be enriched in an on_error statement

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2104]
this will allow context information to be efficiently added to an exception on demand without having to pass the information in an arbitrarily-deep call tree

**Comment by pvanek** [comment]
Btw would it be possible to have exceptions as typed hashes ideally with sort of inheritance? Like eg. in Python /Java

**Comment by davidnich** [comment]
yes that is definitely possible for the future - it's also been on my mind for quite a while

**Comment by gamato** [comment]
Is there inheritance possible with typed hashes?  Because exceptions are objects elsewhere and thus one can filter them nicely via checking if an exception belongs to a certain type (all exceptions belong to the same tree).  So it would be very nice if Qore exceptions were organised in a similar manner.

**Comment by davidnich** [comment]
> Is there inheritance possible with typed hashes?

not yet - should also be implemented in the future - was not implemented for 0.8.13 due to time constraints
