### ISSUE TITLE
the hash version of the map operator is not triggered when the first operand is an empty hash like {}

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#236]
```
david@quasar:~/src/qore/git/qore$ qore -X 'map {}, (1,2)'
list: (2 elements)
  [0]=<EMPTY HASH>
  [1]=<EMPTY HASH>
```

**Comment by tethal** [comment]
It looks like the current implementation of the hash operator expects exactly one key-value pair in the hash, making the following expression a parse error:

```
map {$1 + "_len": $1.length(), $1 + "_first": $1[0]}, ("a", "bb", "ccc")
```

The empty hash can be handled as a special case, but raising a warning seems appropriate since the implementation will completely ignore the other arguments to the map operator.

**Comment by tethal** [comment]
Created #322 for the issue described in the comment
