### ISSUE TITLE
"return hash<name>" requires unnecessary type casting 

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2491]
Even it is fixed I suggest to use _hash to hash<name>_ assignment and operation without annoying typecasting. When unknown a field cannot be assigned then raise error.

```
%new-style

hashdecl LedgerInfo {
    int org_id;
    int ledger_id;
    int set_of_books_id;
    int chart_of_accounts_id;
}


hash<LedgerInfo> sub get_ledger() {
    hash<LedgerInfo> ledger;
    ledger.org_id = 1;
    ledger.ledger_id = 1;
    return ledger;
    #return cast<hash<LedgerInfo>> (ledger);
}

hash<LedgerInfo> ledger = get_ledger();

printf("%y\n", ledger);


unhandled QORE System exception thrown in TID 1 at 2017-11-22 12:29:43.213512 Wed +01:00 (CET) in get_ledger() (/tmp/test-hashdecl.q:15, user code)
RUNTIME-TYPE-ERROR: <return statement> expects type 'hash<LedgerInfo>', but got type 'hash' instead
call stack:
  1: get_ledger() (/tmp/test-hashdecl.q:19, user code)

```

**Comment by davidnich** [comment]
@tmandys ok let's fix this but please note you can fix the error with a small change to the source now:
```
hash<LedgerInfo> sub get_ledger() {
    hash<LedgerInfo> ledger();
    ledger.org_id = 1;
    ledger.ledger_id = 1;
    return ledger;
}
```

note the parens after the `ledger` declaration.

**Comment by davidnich** [comment]
@tmandys this turns out to require an exception due to the way lvalues are handled.  Basically when initializing lvalues, the lvalue "container" can be subject to locking to ensure atomicity - in the case of:
* global variable
* object members
* closure-bound local variables
* local variables used in lvalue reference expressions

In all such cases, Qore uses RW locks to ensure atomicity of operations on those variables.

A hashdecl includes the possibility of defining initializers for each key; we cannot support implicit initialization of hashdecls during lvalue assignments, because we only find out that the lvalue is not assigned while holding the lock, and we cannot execute any Qore code while holding an lvalue lock, as deadlocks can result (and key initialization might be subject to arbitrary code execution).

Therefore the fix here is to introduce a runtime exception in this case.

I would like it to be reviewed to ensure that the consequences are understood. 

I believe the change is necessary because otherwise we have an inconsistency in Qore.

I believe it's better to fix earlier than later as well in order to avoid potential breakage with code that relies on this bug.

I know that you do not like the need for `cast<>` operations, and I agree with you.  The goal though is to reduce the possibility of runtime type errors - this will become much easier when we implement `%strict-types` which will change type semantics a bit, but also make it easier to write an efficient compiler (when we revive the llvm-qore project for example).  With `%strict-types`, all lvalues will always have their declared values if the declared type supports a "default value" (which typed hashes do).   That means that all lvalues with a declared type will always be subject to implicit initialization (or construction) if the type supports a default value.  It also means that when an lvalue is deleted or removed, the lvalue will be "reset" to it's "ground state" or the default value for the declared type.

This is described here: https://github.com/qorelanguage/qore/issues/488

**Comment by martin-zemek** [comment]
It's sad that we cannot write (parse error):
```
hashdecl hd {int i; int j;}
hash<hd> h = {"i": 5, "j": 3};
```
We have to write:
```
hashdecl hd {int i; int j;}
hash<hd> h;
h.i = 5;
h.j = 3;
```

**Comment by davidnich** [comment]
@martin-zemek it's true - this would be nice to write, but then it would mean that a hash could be implicitly converted to a typed hash at runtime which would also leave open the possibility of having more runtime errors such as in cases like:
```
hashdecl hd {int i; int j;}
hash get_hash() {
    return ("a": 1);
}
hd = get_hash();
```

As you can see, the above would result in a runtime error, however it could not be caught at parse time due to the change to support your example.

The whole idea (at least the goal) of strong typing in Qore is to reduce the possibility of runtime type errors to the minimum.

Please note that the current recommended way to achieve what you want to do is:
```
hashdecl hd {int i; int j;}
hash<hd> h(("i": 5, "j": 3));
```

**Comment by sejvlond** [comment]
@davidnich: 
Just a question, why
`hash<hd> h = {"i": 5, "j": 3};`
is not the same as
`hash<hd> h(("i": 5, "j": 3));`

I mean, in C++ assignment to newly declared variable actually calls constructor, and only assignment to existing variable is assignment function. So it can be caught in parse-type, cannot?

Also the first example can be rewritten to 
`hash<hd> xxx(get_hash());`
and this way you cannot get it in parse-time, even if ctor is called. Or am I misunderstanding something?

Thx

**Comment by davidnich** [comment]
@sejvlond 
`{"i": 5, "j": 3}` has type `hash`; in this case, it would be possible for the parser to automatically determine that the immediate hash is compatible with `hash<hd>`, however it's not possible in the case where the hash to be assigned is not an immediate value.

`hash<hd> xxx(get_hash());` will work because the "constructor-type" assignment does the checking at runtime - ex:
```
qore -ne 'hashdecl hd { int i; int j; } hash sub get_hash() { return ("i": 5, "j": 3); } hash<hd> h(get_hash()); printf("%s\n", h.fullType());'
hash<hd>
```

> I mean, in C++ assignment to newly declared variable actually calls constructor, and only assignment to existing variable is assignment function. So it can be caught in parse-type, cannot?

In Qore the assignment to a newly declared variable is the same as any other assignment, which is why there is a difference between Qore and C++.
