### ISSUE TITLE
Debugger: breakpoint assignment is overdefined

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2604]
Breakpoint requires program event then program is already assigned to breakpoint instance

**Comment by davidnich** [comment]
@tmandys what about allowing breakpoints to be created automatically with something like
```
breakpoint "func(int, int)"
```

so the client would send something like `new` as the breakpoint number, and the server then would either create (and enable) a new one and assign the given statement to it - the server's reply would give the breakpoint number used, which could then be displayed in the client.

Otherwise we have an overly complicated procedure for breakpoints - with support like this we could enable a very simple way to create and set breakpoints which also is compatible with other debuggers like gdb and lldb for example.

If you agree, then you can implement this in this issue (if it's related), or we can create a new one.

**Comment by davidnich** [comment]
@tmandys as discussed, I opened #2608 for this other issue
