### ISSUE TITLE
type errors in hash key declarations provide provide confusing results

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2641]
```
        hash xx = (
            'A', :1,    # wrong comma in key
            'B': 2,
            'C̈́': 3,
        );
        printf("%N\n", xx);

hash: (3 members)
   : 1
  B : 2
  C̈́ : 3
```

**Comment by davidnich** [comment]
if you use `%strict-args` then you get a warning at least:
```
david@greybeard:~/src/qore/git/qore/src$ qore -ne '%strict-args
hash xx = (
            "A", :1,    # wrong comma in key
            "B": 2,
            "C̈́": 3,
        );
        printf("%N\n", xx);
'
warning encountered at <command-line>:3
INVALID-OPERATION: key number 0 (starting from 0) in the hash is list<string>, which cannot be converted to a string, therefore will always evaluate to an empty string at runtime
hash: (3 members)
   : 1
  B : 2
  C̈́ : 3
```

Also we cannot just change this to an error as it would potentially break code.  At best it would need to be fixed only with another parse option.  The best one would be the upcoming `%strict-types`, which will enforce must stricter type rules. 

I would prefer to wait until `%strict-types` can be implemented to address this in order to avoid polluting the syntax with excess parse options.

**Comment by davidnich** [comment]
must be implemented with `%strict-types` i.e. #488
