### ISSUE TITLE
module-msgpack: build does not use system provided libraries

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2921]
the package cannot be accepted in Linux distros because it uses builtin copy of libmsgpack
The solution:
cmake should use FindMsgpack.cmake to find system wide library. It can use internal source copy of libmsgpack if it is not found.
It's strongly suggested to use a dedicated directory for 3rd party code instead to mix everything in the qore module src root.

**Comment by omusil24** [comment]
Actually, this module uses https://github.com/ludocode/mpack library, which is not packed anywhere AFAIK, not libmsgpack. Also the last release 0.8.2 is more than 2 years old and it's recommended to use the latest code from master since there has been lots of fixes done there. The library is only 2(+1) files. Not worth it or needed to use anything more complex.

**Comment by pvanek** [comment]
can you, at least, move the 3rd party files to a dedicated (sub)dir with a readme file containing a link to the lib repo and the latest commit hash/tag, please?
The reason why I want this is the future updates.
