### ISSUE TITLE
Adding binary zero as string to existing string will break it.

### ISSUE THREAD

**Issue by petrytar** [qorelanguage/qore#2942]
Adding binary zero as string to existing string will break it.

**Example:**
_string str = "anything";
string zeroByte = <00>.toString();
str += zeroByte; # from this point trying to add anything to "str" will just be ignored_

**Comment by omusil24** [comment]
Adding actually works but since you added `\0` and all the printing etc. goes through printf-like functions, anything after that character doesn't get printed. But it's actually there.

Try running this to see it:
```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

string str = "anything";
printf("%n (size: %d)\n", str, str.size());
string zeroByte = <00>.toString();
str += zeroByte;
printf("%n (size: %d)\n", str, str.size());
str += "abcd";
printf("%n (size: %d)\n", str, str.size());

------------------------ output:
"anything" (size: 8)
"anything" (size: 9)
"anything" (size: 13)
```

**Comment by sejvlond** [comment]
@omusil24 not completely true, @petrytar doesn't showed the best example, look at this:

```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

sub print(string str) {
    for (int i = 0; i < str.size(); ++i) {
        printf("%s (%d)", str[i], ord(str[i]));
    }
    printf("\n");
}

string str = "anything";
print(str);
string zeroByte = <00>.toString();
str += zeroByte;
print(str);
str += "abcd";
print(str);
```

output
```
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103)
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103) (-1)
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103) (-1) (-1) (-1) (-1) (-1)
```

the "abcd" is not here

**Comment by sejvlond** [comment]
maybe the question is: how this should actually behave? is it ok to have a string that has '\0' somewhere in the middle? isn't `binary` is dedicated for such a data? definitely the actual behavior is weird, cause the size of the string is increased but filled with -1

Note, -1 for `ord()` actually means
> Gives the positive numeric value of the given byte in the string passed; if no string is passed or the offset is after the end of the string, -1 is returned. 

that the byte is after the end of the string ... which is probably true, since string is ended with <00>... What do you think? Maybe adding to a string into which was already (manually) added <00> should be a runtime exception?

**Comment by davidnich** [comment]
@sejvlond strings should be able to handle generic binary info with the caveat that if the binary info does not represent valid character data for the string's encoding then an exception will be raised with any character operations that touch that part of the string.  For example UTF-16-encoded strings have embedded nulls in them, and we support UTF-16 generally.

I will look at this hopefully this evening or tomorrow morning and update after that.

**Comment by davidnich** [comment]
@petrytar actually the example works as in:
```
david@greybeard:~/src/qore/git/qore/src$ qore -ne 'string str = "x"; str += <00>.toString(); printf("%d\n", str.size());'
2
```

When you print a string, the output stops at the binary null character, but internally Qore should be able to handle the binary data in the string itself for operations like concatenation etc where no character operations are normally needed (if the strings are tagged with the same encoding at least).

Anyway we know there's a real bug, and I will update this issue when I've had time to investigate.

**Comment by petrytar** [comment]
@davidnich yes, it will not actually break it, but it will forbid some operations on it (e.g. look up in this string will be able just before this zero). Is this because we are using char* in qore language? Is it possible use STD:: string?

**Comment by sejvlond** [comment]
@petrytar it's definitely not because of `char*` cause `std::string` is internally also represented as `char*`, it's more about what we do with it and how.

**Comment by petrytar** [comment]
@sejvlond but adding \0 to string does not mean end of line, and it works fine with such a zeros.

**Comment by davidnich** [comment]
@petrytar we need to use binary searches instead of string searches - i.e. `memmem(3)` instead of `strstr(3)` etc - I think for a reverse search we have to write our own anyway - for strings we have a block of memory with a length + an encoding tag.  For most operations (searches etc) we can do simple binary operations on the buffer after we convert any string to the target encoding if necessary.

Like @sejvlond said, it's not necessarily about using `std::string` over a `char*`, but it would probably be easier to do things with `std::string`, although it would be a big job to port everything properly and ensure that nothing breaks...

However having said that, if I would start over again, I would have definitely used `std::string` over the "do it yourself" approach - same with lists based on `std::vector` etc...

**Comment by davidnich** [comment]
@petrytar from what @sejvlond and I saw in our investigation yesterday, the MIME code needs to use binary searches (`bfind()` etc) instead of character searches; character operations (`<string>::find()`, `<string>::rfind()`; even `[]` on a string is a character operation for example) will fail on strings with embedded nulls and/or binary data - if the string is tagged with a multi-byte encoding like UTF-8 you can get other errors like exceptions when invalid encodings are found.

@sejvlond found a related issue that the null character `0`, which is a valid UTF-8 character, when found in a UTF-8 string, is not being handled as a character (as Qore strings generally use that byte to terminate a string, however when we have binary data in a string, this could theoretically be a character as well, but it's not clear that we should "fix" this when performing character operations on strings with binary data.

**Comment by petrytar** [comment]
@davidnich do we have such search (bfind) ? Or it should be implemented?

**Comment by davidnich** [comment]
@petrytar yes, we have them; we have:
- [bindex()](https://docs.qore.org/current/lang/html/group__string__functions.html#ga1f5360410dc63441327daf2af65b9270)
- [brindex()](https://docs.qore.org/current/lang/html/group__string__functions.html#ga123df73fe420500294a26163371fb175)

However we have no pseudo-methods for this yet in the `<string>` pseudo-class.

**Comment by davidnich** [comment]
we need to decide if there is a real bug here, and if so what to do with it - one choice might be to update the docs - the original issue was caused by using string operations on binary data and solved by using binary operations instead

**Comment by davidnich** [comment]
works when the string is ASCII:
```
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103)
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103)
a (97)n (110)y (121)t (116)h (104)i (105)n (110)g (103)a (97)b (98)c (99)d (100)
"anything"
```
