### ISSUE TITLE
Concatenating binary and string ignores the binary argument without an error or warning

### ISSUE THREAD

**Issue by sejvlond** [qorelanguage/qore#2943]
adding binary to a string is silently ignored
```
$ qore -nX '"xxx" + <4269>'
"xxx"
```

adding string to binary is also silently ignored and the string only is returned
```
 $ qore -nX '<4269> + "xxx"'
"xxx"
```

**Comment by martin-zemek** [comment]
yes, it should act the same as
```
qore -nX '"xxx" + <4269>.toString()' 
"xxxBi"
```

**Comment by sejvlond** [comment]
or it should be an exception/warning in the parse time, that current statement has no meaning and you should explicitly call `.toString()`

**Comment by martin-zemek** [comment]
but you can do
```
qore -nX '"xxx" + 4269' 
"xxx4269"
```

**Comment by sejvlond** [comment]
hm, okay, makes sense. And the opposite version '<4269> + "xx"' should this be converted to ... binary/string?

**Comment by davidnich** [comment]
@sejvlond @martin-zemek we cannot silently support appending binary data to a string, because strings must have an encoding, and it's not safe to assume that the result should use the default encoding when converting binary data to string data.  Therefore in such a case I believe we should throw an exception.

Vice versa could be safe, but it seems like it would make sense to force the programmer to do the conversion explicitly to make sure the intention is what is being executed.

**Comment by davidnich** [comment]
we will implement parse-time and runtime errors for mixing strings & binaries with the `+` and `+=` operators
