### ISSUE TITLE
Improve docs regarding hash keys

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#3107]
The [docs on hashes](https://docs.qore.org/current/lang/html/container_data_types.html#hash) says that keys are strings which isn't entirely true...
```
$ qore -ne 'hash h = {"aaa": "b", 3: 4}; printf("%N\n", h);'
hash: (2 members)
  aaa : "b"
  3 : 4

$ qore -ne 'hash h = {"aaa": "b", 3: 4}; printf("%N\n", h{3});'
4

$ qore -ne 'hash h = {"aaa": "b", 3: 4}; printf("%N\n", h.3);'
4
```

This can be confusing at least. I understand that there probably is some kind of conversion done implicitly but it confuses me that when I print the whole hash, it "knows" that I used an integer as a key to define that value so it's probably not just a one-way conversion.

**Comment by geckon** [comment]
It is in fact a one-way conversion. Only strings are used inside and those integer key above are displayed by %N.

```
$ qore -ne 'hash h = {"aaa": "b", 3: 4}; printf("%N\n", h."3");'
4

$ qore -ne 'hash h = {"aaa": "b", "3": 4}; printf("%N\n", h."3");'
4

$ qore -ne 'hash h = {"aaa": "b", "3": 4}; printf("%N\n", h.3);'
4
```

**Comment by martin-zemek** [comment]
Anything in a position of a hash key is converted to string. You can have `qore -X '{{"a":1}: 3}'`  which gives `{'': 3}` since `{"a":1}.toString() = ''`. or even `qore -X '{NOTHING: 3}'` gives `{'': 3}` since `NOTHING.toString() = ''`.
On the other hand,  `{[1,2]: 3}` produces an exception since `[1,2].toString()` produces an exception.

Actually, the docs on hashes does not literally say that keys must be provided as strings. The formulation "Hashes are containers that associate values to a string key ..." allows for the interpretation:  "keys act as strings".

(By the way, the fact that `NOTHING` can be a hash key makes it possible to chain access to undefined hash indexes, so not only `{"a": 1}.b` is possible but also `{"a":1}.b.c.d` (yes, you'll get a warning but also a result).)

**Comment by martin-zemek** [comment]
As to: ' ...   it "knows" that I used an integer ...':
It does not know that you used an integer, it just prints the string "3" as 3.

**Comment by geckon** [comment]
Thanks for more comments @martin-zemek.

The fact that you can use a hash as a key to another hash seems to be very counter-intuitive, especially since the hash will be converted to an empty string. The same goes for `NOTHING` as a key but there it at least makes (kind of) sense that it's converted to an empty string.
