### ISSUE TITLE
no machine specific macros included (s390x architecture)

### ISSUE THREAD

**Issue by skriesch** [qorelanguage/qore#4655]
The single failing build for qore on openSUSE is the s390x architecture. I have updated qore to the version 1.12.3 in my home repository. The error message is the following:
```

[  713s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build'
[  713s] [ 50%] Building CXX object CMakeFiles/libqore.dir/lib/ConstantList.cpp.o
[  713s] /usr/bin/c++ -DHAVE_UNIX_CONFIG_H -DMODULE_DIR=\"/usr/lib64/qore-modules\" -DMODULE_VER_DIR=\"/usr/lib64/qore-modules/1.12.3\" -DNDEBUG -DUSER_MODULE_DIR=\"/usr/share/qore-modules/\" -DUSER_MODULE_VER_DIR=\"/usr/share/qore-modules/1.12.3\" -D_QORE_LIB_INTERN -Dlibqore_EXPORTS -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build/include -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build/include/qore -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build/include/qore/intern -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include/qore -I/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/lib -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -std=c++11 -O2 -g -DNDEBUG -fPIC -MD -MT CMakeFiles/libqore.dir/lib/ConstantList.cpp.o -MF CMakeFiles/libqore.dir/lib/ConstantList.cpp.o.d -o CMakeFiles/libqore.dir/lib/ConstantList.cpp.o -c /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/lib/ConstantList.cpp
[  713s] In file included from /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include/qore/QoreReferenceCounter.h:37,
[  713s]                  from /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include/qore/AbstractQoreNode.h:37,
[  713s]                  from /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include/qore/Qore.h:57,
[  713s]                  from /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/lib/ConstantList.cpp:31:
[  713s] /home/abuild/rpmbuild/BUILD/qore-release-1.12.3/include/qore/macros.h:56:17: note: '#pragma message: no machine-specific macros included'
[  713s]    56 | #pragma message "no machine-specific macros included"
[  713s]       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  713s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build'
[  714s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/qore-release-1.12.3/build'
[  714s] [ 51%] Building CXX object CMakeFiles/libqore.dir/lib/QoreClassList.cpp.o

```

Build log: https://build.opensuse.org/package/live_build_log/home:AdaLovelace:branches:devel:languages:misc/qore/openSUSE_Factory/s390x

**Comment by davidnich** [comment]
I'll see if I can figure out something that works

**Comment by davidnich** [comment]
I have builds on s390x succeeding after making the following changes:
- added machine-specific macros for S390
- added santiy tests to the spec file
- fixed ppc64 builds - the machine-independent trick for getting the stack pointer from a local variable did not actually work with optimized builds
- Qore now requires native support for getting the stack pointer to build due to the above

However for some reason sanity tests on Fedora 37 for S390 are still failing - related to stack protection code: https://build.opensuse.org/package/live_build_log/home:davidnichols/qore/Fedora_37/s390x - but succeeding for opensuse 14.5: https://build.opensuse.org/package/live_build_log/home:davidnichols/qore/15.4/s390x

Still working on it

**Comment by skriesch** [comment]
Thanks for your effort!
Fedora 37 is released some months ago. openSUSE 15.4 will be replaced with openSUSE 15.5 in the next half year.
That is also a reason for bigger differences.

I would recommend to test openSUSE Tumbleweend with choosing "openSUSE Factory zSystems" under "Add from a distribution". Then you can test  qore for s390x with the latest packages. Fedora 37 is not really old. Therefore, you can reproduce it also with openSUSE Tumbleweed then (I believe it).

**Comment by davidnich** [comment]
I fixed it on F37: https://build.opensuse.org/package/live_build_log/home:davidnichols/qore/Fedora_37/s390x

I added `asm("");` and a dummy static variable in the function that sets up the initial stack pointer to force the compiler not to inline it on s390x, and it looks like it worked.  All tests are passing now on s390x f37.

I'll set up openSUSE Tumbleweed for s390x and check it with that as well.  Looking good now.

**Comment by davidnich** [comment]
Unfortunately the build fails for openSUSE Factory zSystems: https://build.opensuse.org/package/live_build_log/home:davidnichols/qore/openSUSE_Factory_zSystems/s390x

same error - the initial stack pointer is not set properly for new threads...

**Comment by skriesch** [comment]
Is there perhaps a dependency to latest compilers or libraries, that this issue is happening separately on both Linux distributions?

**Comment by davidnich** [comment]
@skriesch with the "best" set of workarounds (not really a fix, because I don't understand the root cause), I have it working on all s390 builds except openSES Factory zSystems.  I'm still looking for a way to make it work there.

My s390x qemu VM is unfortunately not usable for that, as building the RPM crashes there - although manual builds work and were partially useful for debugging - just very slow and in some cases the real HW on build.opensuse.org would show different behavior.  So currently I'm pushing workaround attempts to build.opensuse.org and hoping that I can find the right combination that will make it work in all cases.

The problem is that for some reason qore is not able to get the pointer to the current stack position reliably in new threads on s390x.  It looks like it's related to optimizations somehow, and ensuring a non-inlined call to the function that sets up this data worked up to f37, but is not working on openSUSE Tumbleweed zSystems - I have the feeling that the newer the compiler, the more aggressive the optimizations related to the stack.

**Comment by skriesch** [comment]
I can forward this issue to IBM for s390x support.

**Comment by davidnich** [comment]
@skriesch that would be awesome - I would be very happy for any support on how to do this correctly - basically what Qore does is get the current stack address at the start of each thread - this is done as follows:

```
static inline size_t get_stack_pos() {
    size_t addr;
    __asm("lr %0, 15" : "=r" (addr) );
    return addr;
}
```

Qore also knows the size of the thread's stack.  At runtime, Qore will compare the current stack position against the limit for the thread and throw an exception if the position gets too close to the stack's limit.

The problem is that the call to `get_stack_pos()` at the start of the thread does not work properly on openSUSE Tumbleweed zSystems.  I have no idea why.  Also my qemu s390x VM does not appear to be reliable enough to use for debugging this problem - also it's very slow.

Thanks a lot in advance for any support you can arrange for this issue - I'd be very happy to make this work properly.

**Comment by uweigand** [comment]
Hi @davidnich it seems the core problem is this:
```
    __asm("lr %0, 15" : "=r" (addr) );
```
which copies only the low 32 bits of the stack pointer (instead of all 64 bits).  This may still appear to work if the destination register just so happened to have the correct upper 32 bits already (e.g. if it previously held a pointer to something on the stack).  That's probably why you might accidentally get the correct result depending on the exact compiler version and random code changes.

You should be doing
```
    __asm("lgr %0, 15" : "=r" (addr) );
```
instead.   Once you've done that, none of the other s390-specific changes should be necessary at all.

**Comment by davidnich** [comment]
@uweigand great - thanks a lot!!!

**Comment by davidnich** [comment]
@skriesch @uweigand thanks a lot - everything's working now - a nice simple fix, thanks to your help!

https://build.opensuse.org/package/live_build_log/home:davidnichols/qore/openSUSE_Factory_zSystems/s390x

The fix will go into the next Qore release - currently targeting 1.12.4

**Comment by skriesch** [comment]
Thanks also from my side to @uweigand! That will be a nice Christmas present for our Linux community. :)
