### ISSUE TITLE
wrong comparison of number type values

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#920]
Hmm, this is strange:

```
$ qore -X 'float (1634 + 2517 + 3912 + 4072 + 5813) / 5 == 3589.6'
True
$ qore -X '(1634n + 2517n + 3912n + 4072n + 5813n) / 5'
3589.6
$ qore -X '(1634n + 2517n + 3912n + 4072n + 5813n) / 5n == 3589.6n'
False
```

**Comment by tethal** [comment]
Floating point numbers (that includes qore's `number` type) should never be compared for equality due to their precision. The correct way to check whether `f1` equals to `f2` in any language I know is to first determine an epsilon value, and then do

```
if (abs(f1 - f2) < epsilon) { ... }
```

Unfortunately, there is no universal constant for choosing epsilon - it is application-specific and that's why it is not built in to the language itself.

Try this and you'll see why your expression it is not equal to 3589.6n:

```
qore -X '((1634n + 2517n + 3912n + 4072n + 5813n) / 5).toString(NF_Raw)'
"3589.6000000000000000000000000000000000000000000000000000000000000000000000000009"
```

**Comment by gamato** [comment]
OK, sure.  But NUMBER type is supposed to be of arbitrary precision.  And the result above is wrong.  The correct result is 3589.6 without any extra digits.

**Comment by davidnich** [comment]
@tethal is right and we need to document this - equality comparisons of mathematical operations like this with constant values will fail due to the nature of arbitrary-precision numbers

**Comment by omusil24** [comment]
It is of arbitrary precision. What it means is that you can set how many bits/bytes of precision it should have (which is done inside of Qore). But inside, it's implemented as a floating-point value.

**Comment by gamato** [comment]
OK, then NUMBER is different than what I thought it was.
I thought it would calculate mathematically correct result in the simple example above.

**Comment by tethal** [comment]
As David said, this is a documentation issue - the fact that `number` is a floating-point type is not clear in the documentation ATM
